name: Intro to github actions

on: 
  push: 

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # step prefaite 
      - run: echo "Hello World!" # step home made 